runtime: go
env: flex

automatic_scaling:
  min_num_instances: 1
resources:
  cpu: 1
  memory_gb: 2
  disk_size_gb: 10
#[START env]
env_variables:
  # See https://github.com/go-sql-driver/mysql
  #
  # Replace INSTANCE_CONNECTION_NAME with the same value as in the
  # beta_settings section below.
  MYSQL_CONNECTION: "Junxiang:rmp4vu;6@unix(/cloudsql/xtobu-site:asia-northeast1:site-cloudsql)/Site_db"
 
  #
  # If you're testing locally using the Cloud SQL proxy with TCP,
  # instead use the "tcp" dialer by setting the environment variable:
  # MYSQL_CONNECTION=Junxiang:rmp4vu;6@tcp(127.0.0.1:3306)/junxiang_db
#[END env]

#[START cloudsql_settings]
# Replace INSTANCE_CONNECTION_NAME with the value obtained when configuring your
# Cloud SQL instance, available from the Google Cloud Console or from the Cloud SDK.
# For SQL v2 instances, this should be in the form of "project:region:instance".
# Cloud SQL v1 instances are not supported.
beta_settings:
  cloud_sql_instances: "xtobu-site:asia-northeast1:site-cloudsql"
#[END cloudsql_settings]
